library("shiny")
library("shinythemes")
library("leaflet")
library("DT")
library("shinyWidgets")

rng <- 1965:1980
ui <- fluidPage(
  theme= shinytheme("united"),
  tags$head(
    tags$script(src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.contentWindow.min.js",
                type="text/javascript"),
    tags$script(src="style.css", type=""),
    tags$link(rel = "stylesheet", type = "text/css", href = "style.css")
    
  ),  
  fluidRow(
    column(3, wellPanel(
      selectInput("map.city", "Choose a location:", 
                  c(
                    "All locations" = "All locations",
                    "Alaska" = "AK",
                    "Alabama" = "AL",
                    "Arkansas" = "AR",
                    "Arizona" = "AZ",
                    "California" = "CA",
                    "Colorado" = "CO",
                    "Conneticut" = "CT",
                    "Delaware" = "DE",
                    "Florida" = "FL",
                    "Georgia" = "GA",
                    "Hawaii" = "HI",
                    "Iowa" = "IA",
                    "Idaho" = "ID",
                    "Illinois" = "IL",
                    "Indiana" = "IN",
                    "Kansas" = "KS",
                    "Kentucky" = "KY",
                    "Louisiana" = "LA",
                    "Massachusetts" = "MA",
                    "Maryland" = "MD",
                    "Maine" = "ME",
                    "Mexico" = "Mexcio",
                    "Michigan" = "MI",
                    "Mississippi" = "MS",
                    "Minnesota" = "MN",
                    "Missouri" = "MO",
                    "Montana" = "MT",
                    "Nebraska" = "NE",
                    "New Hampshire" = "NH",
                    "New Jersey" = "NJ",
                    "North Carolina" = "NC",
                    "Nevada" = "NV",
                    "New Mexico" = "NM",
                    "New York" = "NY",
                    "North Dakota" = "ND",
                    "Ohio" = "OH",
                    "Oklahoma" = "OK",
                    "Oregon" = "OR",
                    "Pennsylvania" = "PA",
                    "Rhode Island" = "RI",
                    "South Carolina" = "SC",
                    "South Dakota" = "SD",
                    "Tennessee" = "TN",
                    "Texas" = "TX",
                    "Utah" = "UT",
                    "Virginia" = "VA",
                    "Vermont" = "VT",
                    "Washington" = "WA",
                    "Washington, D.C." = "District of Columbia",
                    "West Virginia" = "WV",
                    "Wisconsin" = "WI",
                    "Wyoming" = "WY"
                    ), selectize=TRUE),
      selectInput("map.am.feature", "Choose an amenity feature:", 
                  c("Show all" = "Show all",
                    "Very Popular - (*)" = "(*)",
                    "After Hours - (AH)" = "(AH)",
                    "At Your Own Risk - Dangerous - Usually Fuzz - (AYOR)" = "(AYOR)",
                    "Blacks Frequent - (B)" = "(B)",
                    "Bare-Ass (Usually nude beach) - (BA)" = "(BA)",
                    "Bring Your Own Bottle - (BYOB)" = "(BYOB)",
                    "Coffee, soft drinks and sometimes snacks - (C)" = "(C)",
                    "Dancing - (D)" = "(D)",
                    "Dangerous - Usually Fuzz (HOT)" = "(HOT)",
                    "Entertainment - (E)" = "(E)",
                    "Final Faith of America, or ask your friendly SM Serviceman - (FFA)" = "(FFA)",
                    "Hotel, Motel, Resort, or other overnight accomodations - (H)" = "(H)",
                    "Girls, but seldom exclusively - (G)" = "(G)",
                    "Heads Frequent - (H)" = "(H)",
                    "Mixed - Some Straights - (M)" = "(M)",
                    "Metropolitan Community Church - (MCC)" = "(MCC)",                  
                    "Older/More Mature Crowd - (OC)" = "(OC)",
                    "Private - Inquire Locally as to Admission - (P)" = "(P)",
                    "Pretty Elegant - Often Coat or Tie - (PE)" = "(PE)",
                    "Pool Table - (PT)" = "(PT)",
                    "Restaurant - (R)" = "(R)",
                    "Raunchy Types - Hustlers, Drags, and other 'Downtown Types' - (RT)" = "(RT)",
                    "Shows--Impersonators or Pantomime Acts--Often Touristy - (S)" = "(S)",
                    "Some Motorcycle & leather - (SM)" = "(SM)",
                    "Western or Cowboy Types - (W)" = "(W)",
                    "Weekends - (WE)" = "(WE)",
                    "Young/Collegiate Types - (YC)" = "(YC)",
                    "Cruisy Areas" = "Cruisy Area"
                  ), 
                  selected = "Show all", multiple = FALSE, selectize = TRUE, width = NULL, size = NULL),
        selectInput("map.type", "Choose a location type: ", c(
              "Show all" = "Show all",
              "Bars or Clubs" = "Bars/Clubs",
              "Bathhouses" = "Baths",
              "Hotels" = "Hotel",
              "Hotel Bars" = "Hotel Bar",
              "Cruising Areas", "Cruising Areas",
              "Restaurants" = "Restaurant",
              "Book Store" = "Book Store",
              "Theatre" = "Theatre",
              "Business" = "Business",
              "Religious Instituion" = "Church"
        )), 
      checkboxInput("filter.verified", "Show only verified locations?", value = FALSE),
      actionButton("reset_button", "Reset Filters",
                   icon = icon("repeat"), class = "btn-warning btn-sm"),
      includeHTML("about.html")
    )),
    
    column(9,
           leafletOutput("spaces_map"),
           sliderTextInput("map.year", "Year",
                           choices = rng,
                           selected = rng[1],
                           grid = T,
                           width = "100%"),
           conditionalPanel(
             condition = "input['map.year'] == 1967",
             includeHTML("nodatanotice.html")
           )),
          h5(textOutput("num.locations")),  
    dataTableOutput("spaces.table", width="100%", height="auto")
  ),
  HTML('<div data-iframe-height></div>')
  
)

